/**
 * @file seedData.js
 * @description Master agronomic seed data for Indian Agriculture.
 * Contains verified crops, fertilizers, insect pests/pathogens, and APMC mandi market data.
 */

const cropsSeed = [
  {
    cropName: 'wheat',
    displayName: 'Wheat (Kalyan Sona / PBW-343)',
    season: 'Rabi',
    idealSoilType: ['alluvial', 'loamy', 'black_cotton', 'clay'],
    waterRequirement: 450,
    temperature: { min: 10, max: 25 },
    harvestingPeriod: 120,
    expectedYield: 22,
    seedCost: 1500,
    fertilizerCost: 3200,
    laborCost: 4500,
    marketDemand: 'High',
    suitableStates: ['Punjab', 'Haryana', 'Uttar Pradesh', 'Madhya Pradesh', 'Rajasthan', 'Bihar'],
    description: 'Premier cereal crop of Northern India, highly suitable for irrigated alluvial plains.',
  },
  {
    cropName: 'rice',
    displayName: 'Rice / Paddy (Basmati / IR-64)',
    season: 'Kharif',
    idealSoilType: ['alluvial', 'clay', 'loamy', 'black_cotton'],
    waterRequirement: 1200,
    temperature: { min: 20, max: 38 },
    harvestingPeriod: 130,
    expectedYield: 25,
    seedCost: 1800,
    fertilizerCost: 4000,
    laborCost: 6500,
    marketDemand: 'High',
    suitableStates: ['Punjab', 'West Bengal', 'Uttar Pradesh', 'Andhra Pradesh', 'Bihar', 'Odisha'],
    description: 'Staple food crop of India with high water requirement and guaranteed MSP procurement.',
  },
  {
    cropName: 'cotton',
    displayName: 'Bt Cotton (Cash Crop)',
    season: 'Kharif',
    idealSoilType: ['black_cotton', 'alluvial', 'red'],
    waterRequirement: 700,
    temperature: { min: 21, max: 35 },
    harvestingPeriod: 160,
    expectedYield: 14,
    seedCost: 2400,
    fertilizerCost: 4200,
    laborCost: 7500,
    marketDemand: 'High',
    suitableStates: ['Gujarat', 'Maharashtra', 'Telangana', 'Andhra Pradesh', 'Madhya Pradesh', 'Punjab'],
    description: 'White gold commercial cash crop thriving on deep black cotton soil.',
  },
  {
    cropName: 'mustard',
    displayName: 'Mustard / Sarson (Pusa Bold)',
    season: 'Rabi',
    idealSoilType: ['alluvial', 'sandy', 'loamy'],
    waterRequirement: 300,
    temperature: { min: 10, max: 25 },
    harvestingPeriod: 105,
    expectedYield: 9,
    seedCost: 900,
    fertilizerCost: 2200,
    laborCost: 3000,
    marketDemand: 'High',
    suitableStates: ['Rajasthan', 'Uttar Pradesh', 'Haryana', 'Madhya Pradesh', 'Punjab'],
    description: 'High-oil content winter cash crop requiring low water and high cold tolerance.',
  },
  {
    cropName: 'maize',
    displayName: 'Maize / Corn (HQPM-1)',
    season: 'Kharif',
    idealSoilType: ['alluvial', 'red', 'loamy'],
    waterRequirement: 500,
    temperature: { min: 18, max: 32 },
    harvestingPeriod: 95,
    expectedYield: 26,
    seedCost: 1600,
    fertilizerCost: 3500,
    laborCost: 4000,
    marketDemand: 'Medium',
    suitableStates: ['Karnataka', 'Madhya Pradesh', 'Bihar', 'Rajasthan', 'Telangana', 'Uttar Pradesh'],
    description: 'Versatile food, feed, and industrial starch crop with short duration.',
  },
  {
    cropName: 'gram',
    displayName: 'Chickpea / Desi Chana (JG-11)',
    season: 'Rabi',
    idealSoilType: ['black_cotton', 'loamy', 'alluvial'],
    waterRequirement: 250,
    temperature: { min: 12, max: 28 },
    harvestingPeriod: 110,
    expectedYield: 10,
    seedCost: 2000,
    fertilizerCost: 1500,
    laborCost: 3200,
    marketDemand: 'High',
    suitableStates: ['Madhya Pradesh', 'Maharashtra', 'Rajasthan', 'Uttar Pradesh', 'Karnataka'],
    description: 'Nitrogen-fixing pulse crop enriching soil fertility with minimal irrigation.',
  },
  {
    cropName: 'sugarcane',
    displayName: 'Sugarcane (Co-0238)',
    season: 'Perennial',
    idealSoilType: ['alluvial', 'black_cotton', 'loamy'],
    waterRequirement: 1800,
    temperature: { min: 20, max: 40 },
    harvestingPeriod: 330,
    expectedYield: 350,
    seedCost: 8000,
    fertilizerCost: 11000,
    laborCost: 18000,
    marketDemand: 'High',
    suitableStates: ['Uttar Pradesh', 'Maharashtra', 'Karnataka', 'Tamil Nadu', 'Bihar'],
    description: 'Long duration high-revenue cash crop supported by local sugar mills.',
  },
  {
    cropName: 'groundnut',
    displayName: 'Groundnut / Peanuts (Kadiri-6)',
    season: 'Kharif',
    idealSoilType: ['sandy', 'red', 'loamy'],
    waterRequirement: 450,
    temperature: { min: 22, max: 32 },
    harvestingPeriod: 115,
    expectedYield: 12,
    seedCost: 3200,
    fertilizerCost: 2600,
    laborCost: 4500,
    marketDemand: 'High',
    suitableStates: ['Gujarat', 'Andhra Pradesh', 'Tamil Nadu', 'Rajasthan', 'Karnataka'],
    description: 'Important oilseed and legume flourishing in light sandy-loam soils.',
  },
];

const fertilizersSeed = [
  {
    name: 'Urea',
    npkRatio: { n: 46, p: 0, k: 0 },
    costPerBag: 266.5,
    bagWeightKg: 45,
    dosagePerAcre: 65,
    applicationMethod: 'Top Dressing',
    bestTiming: 'Split application: 1/3 at basal sowing, 1/3 at first irrigation, 1/3 at tillering stage.',
    description: 'Primary source of Nitrogen for robust vegetative plant growth.',
  },
  {
    name: 'DAP (Di-Ammonium Phosphate)',
    npkRatio: { n: 18, p: 46, k: 0 },
    costPerBag: 1350,
    bagWeightKg: 50,
    dosagePerAcre: 50,
    applicationMethod: 'Basal Dressing',
    bestTiming: 'Apply below the seed row at time of sowing or transplanting.',
    description: 'Concentrated Phosphorus source vital for root establishment and early vigor.',
  },
  {
    name: 'MOP (Muriate of Potash)',
    npkRatio: { n: 0, p: 0, k: 60 },
    costPerBag: 1700,
    bagWeightKg: 50,
    dosagePerAcre: 30,
    applicationMethod: 'Basal Dressing',
    bestTiming: 'Apply during final soil preparation before sowing or pre-flowering.',
    description: 'Potassium nutrient for disease resistance, drought tolerance, and grain weight.',
  },
  {
    name: 'SSP (Single Super Phosphate)',
    npkRatio: { n: 0, p: 16, k: 0 },
    costPerBag: 500,
    bagWeightKg: 50,
    dosagePerAcre: 100,
    applicationMethod: 'Basal Dressing',
    bestTiming: 'Apply broadcast before tillage.',
    description: 'Contains 16% P and 11% Sulphur, ideal for oilseeds and pulses.',
  },
  {
    name: 'NPK Complex (10:26:26)',
    npkRatio: { n: 10, p: 26, k: 26 },
    costPerBag: 1470,
    bagWeightKg: 50,
    dosagePerAcre: 50,
    applicationMethod: 'Basal Dressing',
    bestTiming: 'Apply at sowing time for high phosphate & potash demanding crops.',
    description: 'Balanced fertilizer formulation for fruits, vegetables, and tuber crops.',
  },
  {
    name: 'Neem Cake (Organic Fertilizer)',
    npkRatio: { n: 5, p: 1, k: 1.5 },
    costPerBag: 800,
    bagWeightKg: 50,
    dosagePerAcre: 150,
    applicationMethod: 'Broadcasting',
    bestTiming: 'Mix with topsoil 15 days before seed sowing.',
    description: 'Organic bio-fertilizer and natural soil pest repellent against nematodes.',
  },
];

const pestsSeed = [
  {
    pestName: 'Yellow Stem Borer',
    scientificName: 'Scirpophaga incertulas',
    affectedCrops: ['rice', 'paddy'],
    symptoms: 'Dead hearts in early vegetative stage, white heads (empty chaffy panicles) at maturity.',
    severity: 'severe',
    treatment: {
      organic: 'Release egg parasitoid Trichogramma japonicum @ 50,000/ha or install pheromone traps @ 8/acre.',
      chemical: 'Apply Cartap Hydrochloride 4G @ 10 kg/acre or Chlorantraniliprole 18.5% SC @ 60 ml/acre.',
    },
    treatmentCostPerAcre: 750,
    preventiveMeasures: 'Clip seedling tips before transplanting; avoid excess urea application; drain stagnant water.',
    seasonalOccurrence: 'Kharif',
  },
  {
    pestName: 'Aphids / Mahu',
    scientificName: 'Lipaphis erysimi',
    affectedCrops: ['mustard', 'wheat', 'cotton', 'gram'],
    symptoms: 'Clusters of small green/black insects sucking sap from leaves, curled foliage, sooty mold growth.',
    severity: 'moderate',
    treatment: {
      organic: 'Spray Neem Oil 10,000 PPM @ 3 ml/liter with liquid detergent or release ladybird beetles.',
      chemical: 'Spray Imidacloprid 17.8% SL @ 60 ml/acre or Thiamethoxam 25% WG @ 80 g/acre.',
    },
    treatmentCostPerAcre: 420,
    preventiveMeasures: 'Early sowing by mid-October; install yellow sticky traps @ 10/acre.',
    seasonalOccurrence: 'Rabi',
  },
  {
    pestName: 'Pink Bollworm',
    scientificName: 'Pectinophora gossypiella',
    affectedCrops: ['cotton'],
    symptoms: 'Rosetted flowers, bored holes on bolls plugged with excreta, stained lint and damaged seeds.',
    severity: 'severe',
    treatment: {
      organic: 'Install gossyplure pheromone traps @ 5/acre and spray Bacillus thuringiensis (Bt) formulation.',
      chemical: 'Spray Emamectin Benzoate 5% SG @ 100 g/acre or Profenophos 50% EC @ 400 ml/acre.',
    },
    treatmentCostPerAcre: 950,
    preventiveMeasures: 'Strictly observe 150-day crop cycle; avoid ratoon cropping; dispose of infested bolls.',
    seasonalOccurrence: 'Kharif',
  },
  {
    pestName: 'Yellow Rust / Stripe Rust',
    scientificName: 'Puccinia striiformis',
    affectedCrops: ['wheat'],
    symptoms: 'Yellow stripe-like pustules arranged along leaf veins; yellow dust easily smudges onto fingers.',
    severity: 'severe',
    treatment: {
      organic: 'Spray Sour Buttermilk (Chhachh) solution (5% concentration) with fermented neem extract.',
      chemical: 'Spray Propiconazole 25% EC (Tilt) @ 200 ml in 200 liters of water per acre immediately on notice.',
    },
    treatmentCostPerAcre: 680,
    preventiveMeasures: 'Grow rust-resistant varieties (HD-2967, PBW-550); monitor fields regularly during cool misty mornings.',
    seasonalOccurrence: 'Rabi',
  },
  {
    pestName: 'Fall Armyworm',
    scientificName: 'Spodoptera frugiperda',
    affectedCrops: ['maize', 'sugarcane'],
    symptoms: 'Ragged leaves with shot-holes, heavy sawdust-like frass inside the central leaf whorl.',
    severity: 'severe',
    treatment: {
      organic: 'Apply whorl application of sand and lime mixture (9:1) or spray Metarhizium rileyi fungus.',
      chemical: 'Whorl application of Chlorantraniliprole 18.5% SC @ 80 ml/acre or Spinetoram 11.7% SC @ 100 ml/acre.',
    },
    treatmentCostPerAcre: 880,
    preventiveMeasures: 'Synchronized deep summer plowing; intercrop with cowpea or pigeon pea; install FAW lures.',
    seasonalOccurrence: 'Kharif',
  },
];

const marketPricesSeed = [
  {
    cropName: 'wheat',
    market: 'Khanna Grain Mandi',
    state: 'Punjab',
    district: 'Ludhiana',
    price: 2425,
    minPrice: 2350,
    maxPrice: 2500,
    priceChangePercentage: 2.1,
  },
  {
    cropName: 'wheat',
    market: 'Najafgarh Mandi',
    state: 'Delhi',
    district: 'South West Delhi',
    price: 2470,
    minPrice: 2400,
    maxPrice: 2550,
    priceChangePercentage: 1.2,
  },
  {
    cropName: 'rice',
    market: 'Karnal Anaj Mandi',
    state: 'Haryana',
    district: 'Karnal',
    price: 3650,
    minPrice: 3400,
    maxPrice: 3800,
    priceChangePercentage: -0.8,
  },
  {
    cropName: 'cotton',
    market: 'Rajkot APMC Mandi',
    state: 'Gujarat',
    district: 'Rajkot',
    price: 7250,
    minPrice: 6900,
    maxPrice: 7550,
    priceChangePercentage: 3.4,
  },
  {
    cropName: 'mustard',
    market: 'Alwar Krishi Upaj Mandi',
    state: 'Rajasthan',
    district: 'Alwar',
    price: 5400,
    minPrice: 5200,
    maxPrice: 5650,
    priceChangePercentage: 1.5,
  },
  {
    cropName: 'maize',
    market: 'Chhindwara Mandi',
    state: 'Madhya Pradesh',
    district: 'Chhindwara',
    price: 2150,
    minPrice: 2000,
    maxPrice: 2280,
    priceChangePercentage: 0.5,
  },
  {
    cropName: 'gram',
    market: 'Indore Mandi',
    state: 'Madhya Pradesh',
    district: 'Indore',
    price: 6100,
    minPrice: 5900,
    maxPrice: 6300,
    priceChangePercentage: 2.8,
  },
];

module.exports = {
  cropsSeed,
  fertilizersSeed,
  pestsSeed,
  marketPricesSeed,
};
